version: '3.3'

services:
  app:
    image: gsong/djangogirls-app
    container_name: djangogirls-app
    env_file: .env
    command: ./manage.py runserver 0.0.0.0:${APP_PORT:-8000}
    volumes:
      - ${HOME}/Desktop:/root/Desktop:ro
      - ./.data/services/app/bash_history:/root/.bash_history
      - ./.data/services/app/ipython/:/root/.ipython
      - .:/root/src/djangogirls
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
